### ISSUE TITLE
When updating a use case, setting the Score threshold to DISABLED does not seem to take effect.

### ISSUE THREAD

**Issue by hiraken-w** [aws-solutions/generative-ai-application-builder-on-aws#154] opened 2024-10-05 18:45 UTC
**Describe the bug**

As per the following documentation, we can configure Kendra's Advanced RAG configurations. However, once we set the Score threshold to a value other than DISABLED, like LOW, we cannot revert it back to DISABLED in subsequent updates. On the web app, there is no error shown, and it appears to be successful, but the change is not reflected.

https://docs.aws.amazon.com/solutions/latest/generative-ai-application-builder-on-aws/advanced-knowledge-base-settings.html

If we update to set the Score threshold to DISABLED, the request body for the PATCH method to API Gateway does not include the ScoreThreshold parameter. In this case, it is considered necessary to perform processing such as deleting the item keys (ScoreThreshold, StorageCapacityUnits) from the DynamoDB table.

**To Reproduce**

1. Create a Generative AI Application Builder.
2. Deploy a new use case. Leave the default settings as is. Select Kendra for the Knowledge base type, and set a value other than DISABLED for the Score Threshold in Advanced RAG configurations.
3. Update the use case. Set DISABLED for the Score Threshold in Advanced RAG configurations.

As a result, the Score Threshold does not become DISABLED.

**Expected behavior**

The Score Threshold value in Advanced RAG configurations can be updated to DISABLED.

**Please complete the following information about the solution:**

- [x] Version: v2.0.4
- [x] Region: us-east-1
- [x] Was the solution modified from the version published on this repository?: No changes have been made.
- [x] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?: This is not a service quota issue.
- [x] Were there any errors in the CloudWatch Logs?: The Lambda function's create_config_string execution was successful.

**Comment by ihmaws** [comment] 2024-10-06 00:59
Thank you @hiraken-w for the detailed bug report!

I was able to reproduce the issue and identify the root cause. The team will have a look at a fix and include a patch in our next release.

We'll let you know here once a fix is available. Thanks again!

**Comment by jamesnixon-aws** [comment] 2024-11-20 19:45
Issue resolved in release v2.1.0

**Closed by jamesnixon-aws** 2024-11-20 19:45 UTC
Labels: bug
